#!/bin/fish

# --------------------------------------------------------------------------------------------------
# COLORPICKER
# --------------------------------------------------------------------------------------------------
function colorpicker
    set theme ~/.config/rofi/colorpicker.rasi

    killall -q rofi

    # Options
    set hex_opt hex
    set rgb_opt rgb
    set hsl_opt hsl

    # Variables passed to dmenu
    set options "$hex_opt\n$rgb_opt\n$hsl_opt"
    set opt (echo -e "$options" | rofi -dmenu -p "xcolor" -theme $theme)

    if test -z $opt
        exit 0
    end

    ~/.config/awesome/scripts/utils xcolor $opt
end

# --------------------------------------------------------------------------------------------------
# ZATHURA DOCUMENTS HISTORY
# --------------------------------------------------------------------------------------------------
function docs
    set theme ~/.config/rofi/documents.rasi
    killall -q rofi
    set zathura_history (cat ~/.local/share/zathura/history | grep -Po "\[\K[^\]]*" | grep "/home/")

    if test -z "$zathura_history"
        set history "You have read no documents"
    end

    set opt (printf "%s\n" $zathura_history | rofi -dmenu -p "zathura" -theme $theme)

    if test -z $opt
        exit 0
    end

    zathura $opt
    exit 0
end

# --------------------------------------------------------------------------------------------------
# LAUNCHER
# --------------------------------------------------------------------------------------------------
function launcher
    set theme ~/.config/rofi/launcher.rasi
    killall -q rofi
    set opt (rofi -show drun -theme $theme)

    if test -z $opt
        exit 0
    end
end

# --------------------------------------------------------------------------------------------------
# POWER MENU
# --------------------------------------------------------------------------------------------------
function powermenu
    set theme ~/.config/rofi/powermenu.rasi
    set uptime (uptime -p | sed -e 's/up //g')

    killall -q rofi

    # options
    set suspend ""
    set lock ""
    set logout ""
    set reboot ""
    set shutdown ""

    # variables passed to dmenu
    set options "$suspend\n$lock\n$logout\n$reboot\n$shutdown"

    set opt (echo -e $options | rofi -dmenu -p "Uptime: $uptime" -theme $theme -selected-row 2)

    if test -z $opt
        exit 0
    end

    switch $opt
        case $shutdown
            poweroff
        case $reboot
            reboot
        case $logout
            awesome-client "awesome.quit()"
        case $lock
            ~/.config/awesome/scripts/utils lock
        case $suspend
            systemctl suspend
    end
end

# --------------------------------------------------------------------------------------------------
# CAPTURE
# --------------------------------------------------------------------------------------------------
function capture
    set sct ~/.config/awesome/scripts/screencapture
    set theme ~/.config/rofi/capture.rasi
    killall -q rofi

    # Options
    set full ""
    set area ""

    # Variables passed to dmenu
    set options "$full\n$area"

    set opt (echo -e $options | rofi -dmenu -p "ffmpeg" -theme $theme)

    if test -z $opt
        exit 0
    end

    switch $opt
        case $full
            $sct full
        case $area
            $sct area
    end

end

# --------------------------------------------------------------------------------------------------
# SCREENSHOT
# --------------------------------------------------------------------------------------------------
function screenshot
    set sct ~/.config/awesome/scripts/screensht
    set theme ~/.config/rofi/screenshot.rasi
    killall -q rofi

    # Options
    set full ""
    set area ""
    set focused ""

    # Variables passed to dmenu
    set options "$full\n$area\n$focused"

    set opt (echo -e $options | rofi -dmenu -p "maim" -theme $theme)

    if test -z $opt
        exit 0
    end

    switch $opt
        case $full
            $sct full
        case $area
            $sct area
        case $focused
            $sct focused
    end
end

# --------------------------------------------------------------------------------------------------
# WINDOW PICKER
# --------------------------------------------------------------------------------------------------
function windowpicker
    set theme ~/.config/rofi/windows.rasi
    killall -q rofi
    set opt (rofi -show window -theme $theme)

    if test -z $opt
        exit 0
    end
end

switch $argv[1]
    case colorpicker
        colorpicker
    case docs
        docs
    case launcher
        launcher
    case powermenu
        powermenu
    case capture
        capture
    case screenshot
        screenshot
    case windowpicker
        windowpicker
end
