#!/bin/fish

set SCREENSHOT_DIR (xdg-user-dir PICTURES)/Screenshots
mkdir -p $SCREENSHOT_DIR

if test -z (command -v maim)
    awesome-client "
    local naughty = require('naughty')
    naughty.notification({
      title = 'Missing dependency: maim',
      app_name = 'Screenshot'
    })
  "
    exit 1
end

if test -z (command -v xdotool)
    awesome-client "
    local naughty = require('naughty')
    naughty.notification({
      title = 'Missing dependency: xdotool',
      app_name = 'Screenshot'
    })
  "
    exit 1
end

function summary
    set target $argv[1]
    xclip -selection clipboard -t image/png -i $target
    awesome-client "
	    -- IMPORTANT NOTE: THIS PART OF THE SCRIPT IS LUA!
	    naughty = require('naughty')
	    awful = require('awful')

	    local open_image = naughty.action {
	    	name = 'Open',
	       	icon_only = false,
	    }

	    local delete_image = naughty.action {
	    	name = 'Delete',
	       	icon_only = false,
	    }

	    -- Execute the callback when 'Open' is pressed
	    open_image:connect_signal('invoked', function()
	    	awful.spawn('imv ' .. '$target', false)
	    end)

	    -- Execute the callback when 'Delete' is pressed
	    delete_image:connect_signal('invoked', function()
	    	awful.spawn('gio trash ' .. '$target', false)
	    end)

	    -- Show notification
	    naughty.notification ({
	    	title = 'Cluck!',
        message = 'A screenshot saved and copied to clipboard',
	    	app_name = 'Screenshot',
	    	icon = '$target',
	    	timeout = 10,
	    	actions = { open_image, delete_image }
	    })
	    "
end

function full
    set timestamp (date "+%Y%m%d_%H%M%S")
    set file "$SCREENSHOT_DIR/$timestamp-full.png"
    maim -d 1 $file
    summary $file
end

function area
    set timestamp (date "+%Y%m%d_%H%M%S")
    set file "$SCREENSHOT_DIR/$timestamp-area.png"
    maim -d 1 -s $file
    summary $file
end

function focused
    set timestamp (date "+%Y%m%d_%H%M%S")
    set file "$SCREENSHOT_DIR/$timestamp-focused.png"
    maim -d 1 -i $(xdotool getactivewindow) $file
    summary $file
end

switch $argv[1]
    case full
        full
    case area
        area
    case focused
        focused
    case *
        full
end
