#!/bin/fish

function nightlight-off
    set state (pgrep redshift)

    if test -n "$state"
        redshift -x &>/dev/null && pkill redshift && killall redshift
        echo off
    end
end

function nightlight-on
    set state (pgrep redshift)
    if test -z "$state"
        redshift -l 0:0 -t 5250:5000 -r &>/dev/null &
        echo on
    end
end

function lock
    awesome-client "require('modules.lockscreen.lockscreen')()"
end

function idle-inhibit-off
    xset -dpms
    xset s off
end

function idle-inhibit-on
    xset +dmps
    xset s default
end

function xcolor
    if test -z (command -v gpick)
        awesome-client "
          local naughty = require('naughty')
          naughty.notification({
            title = 'Missing dependency: gpick',
            app_name = 'Color Picker',
          })
        "
        exit 1
    end

    awesome-client "require('utils.xcolor').pick('$argv[1]')"
end

switch $argv[1]
    case xcolor
        xcolor $argv[2]

    case nightlight
        switch $argv[2]
            case on
                nightlight-on
            case off
                nightlight-off
        end

    case idle-inhibit
        switch $argv[2]
            case on
                idle-inhibit-on
            case off
                idle-inhibit-off
        end

    case lock
        lock
end
