#!/bin/fish

function nightlight
    set state (pgrep redshift)

    if test -n "$state"
        redshift -x && pkill redshift && killall redshift
        echo off
    else
        redshift -l 0:0 -t 5250:5000 -r &>/dev/null &
        echo on
    end
end

switch $argv[1]
    case nightlight
        nightlight
end
